# Generated by Django 3.0.7 on 2020-07-21 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200706_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
