# Generated by Django 3.0.7 on 2020-07-21 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200721_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
