# Generated by Django 3.0.7 on 2020-07-21 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200721_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='date_posted',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
