# Generated by Django 3.0.7 on 2020-07-25 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200721_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweets',
            old_name='id',
            new_name='tweet_id',
        ),
    ]
