# Generated by Django 3.0.7 on 2020-07-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200725_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='tweet_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
